version: '3.7'

services:
    pgsql:
        image: postgres:13
        ports:
          - '$DB_PORT:5432'
        container_name: 'pgsql'
        restart: always
        volumes:
          - pg-data:/var/lib/postgresql/data
        env_file: .env
        networks:
            - app-network

    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: nodejs
        container_name: api
        restart: unless-stopped
        env_file: .env
        environment: 
            - DB_HOST=pgsql
        ports:
            - "$PORT:3000"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        command: npm run start:dev
        depends_on:
            - pgsql
        networks:
            - app-network
        
networks:
    app-network:
        driver: bridge

volumes:
    pg-data:
    node_modules:
