name: Test inside Docker

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Run the Docker image
              run: docker-compose -f docker-test.yml up