name: Api Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set ENV variables
              run: for v in `cat env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
              
            - name: Build the Docker image
              run: docker-compose build test

            - name: Run the Docker image
              run: docker-compose run test

              